### PR TITLE
Reintegrate next

### PR DESCRIPTION
**Pull request by gilligan**
This is a rebase of next on master which fixes the tests and also updates the README with the new features introduced by the next branch.

### CODE REVIEW

**Comment by gilligan** [comment]
@paldepind this time I am responsible for the delay. As discussed this PR goes against the `next` branch.

**Comment by paldepind** [comment]
Really great! Thank you.

**Comment by paldepind** [comment]
There is something odd here. The recent commits by @kurtharriger are not included here.

**Comment by gilligan** [comment]
Urghs. Sorry if I messed it up. Everything was fine with the PR against master then I was in a hurry to fix it to go against next instead. I have to check again. Will try to do so this afternoon or evening

**Comment by paldepind** [comment]
I think I've managed to get it sorted out myself :)

**Comment by gilligan** [comment]
Alright. Sorry again

**Pull request merged**
